id: PDBFDBDDD
initial_creation_type: ocr
source_metadata:
  volumes:
    b2a99b36bb474dcbad293b07163810f3:
      base_file: v046.txt
      image_group_id: I1PD95891
      title: ''
      total_pages: 1201
      volume_number: 46
